# Generated by Django 3.2 on 2021-04-17 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='pics', validators=[django.core.validators.FileExtensionValidator(['JPEG', 'PNG']), django.core.validators.validate_image_file_extension]),
        ),
    ]
