# Generated by Django 3.2 on 2021-04-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210427_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=models.FilePathField(blank=True, null=True, path='/media/pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=models.FilePathField(blank=True, null=True, path='/media/pics'),
        ),
    ]
