# Generated by Django 3.2 on 2021-04-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210427_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=models.FilePathField(blank=True, null=True, path='api/media/pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=models.FilePathField(blank=True, null=True, path='api/media/pics'),
        ),
    ]
