# Generated by Django 3.2 on 2021-04-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210428_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media/pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media/pics'),
        ),
    ]
