# Generated by Django 3.2 on 2021-04-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210428_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=models.FilePathField(blank=True, null=True, path='/C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media/pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=models.FilePathField(blank=True, null=True, path='/C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media/pics'),
        ),
    ]
