# Generated by Django 3.2 on 2021-04-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210428_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_200',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media\\pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_400',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\Dagmara\\Desktop\\kodilla\\Python\\Projekty\\hexocean\\django-api\\myapi\\media\\pics'),
        ),
    ]
