# Generated by Django 3.2 on 2021-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210501_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail_200',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
