# Generated by Django 3.2 on 2021-05-09 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0014_auto_20210502_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('type', models.CharField(choices=[('B', 'Base'), ('P', 'Premium'), ('E', 'Enterprise'), ('C', 'Custom')], default='B', max_length=1)),
                ('small_thmb_size', models.IntegerField(default=200)),
                ('big_thmb_size', models.IntegerField(default=400)),
                ('has_original_img', models.BooleanField(default=False)),
                ('has_expiring_links', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.account')),
                ('link', models.URLField(blank=True, null=True)),
                ('link_max_life', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(30)])),
                ('link_start', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
